Feat remove punct
UBC-MDS/textprepr pull request #9
Opened 2022-01-20 06:47 UTC by PhilsChan

Add function spec for `remove_punct()` function

2022-01-20 08:38 UTC, joshsia commented on R/remove_punct.R
> +#' Generate word cloud
I think you forgot to change this

2022-01-20 08:39 UTC, joshsia requested changes
I think you forgot to change the first line of `remove_punct.R`

2022-01-20 08:39 UTC, joshsia commented on R/remove_punct.R
> +#' Generate word cloud
I think you forgot to change this

2022-01-20 23:24 UTC, joshsia approved these changes

2022-01-21 00:08 UTC, arijc76 approved these changes

2022-01-21 05:54 UTC, merged